language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
 - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
 - composer install --dev

script:
 - phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#zftalk.2"
